/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsTestRouteImport } from './routes/tools-test'
import { Route as MiddlewareTestRouteImport } from './routes/middleware-test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderIndexRouteImport } from './routes/$provider/index'
import { Route as ApiVideoRouteImport } from './routes/api.video'
import { Route as ApiTtsRouteImport } from './routes/api.tts'
import { Route as ApiTranscriptionRouteImport } from './routes/api.transcription'
import { Route as ApiToolsTestRouteImport } from './routes/api.tools-test'
import { Route as ApiSummarizeRouteImport } from './routes/api.summarize'
import { Route as ApiMiddlewareTestRouteImport } from './routes/api.middleware-test'
import { Route as ApiImageRouteImport } from './routes/api.image'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ProviderFeatureRouteImport } from './routes/$provider/$feature'
import { Route as ApiVideoStreamRouteImport } from './routes/api.video.stream'
import { Route as ApiTtsStreamRouteImport } from './routes/api.tts.stream'
import { Route as ApiTranscriptionStreamRouteImport } from './routes/api.transcription.stream'
import { Route as ApiImageStreamRouteImport } from './routes/api.image.stream'

const ToolsTestRoute = ToolsTestRouteImport.update({
  id: '/tools-test',
  path: '/tools-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MiddlewareTestRoute = MiddlewareTestRouteImport.update({
  id: '/middleware-test',
  path: '/middleware-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({
  id: '/$provider/',
  path: '/$provider/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoRoute = ApiVideoRouteImport.update({
  id: '/api/video',
  path: '/api/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscriptionRoute = ApiTranscriptionRouteImport.update({
  id: '/api/transcription',
  path: '/api/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsTestRoute = ApiToolsTestRouteImport.update({
  id: '/api/tools-test',
  path: '/api/tools-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummarizeRoute = ApiSummarizeRouteImport.update({
  id: '/api/summarize',
  path: '/api/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMiddlewareTestRoute = ApiMiddlewareTestRouteImport.update({
  id: '/api/middleware-test',
  path: '/api/middleware-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderFeatureRoute = ProviderFeatureRouteImport.update({
  id: '/$provider/$feature',
  path: '/$provider/$feature',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoStreamRoute = ApiVideoStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiVideoRoute,
} as any)
const ApiTtsStreamRoute = ApiTtsStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiTtsRoute,
} as any)
const ApiTranscriptionStreamRoute = ApiTranscriptionStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiTranscriptionRoute,
} as any)
const ApiImageStreamRoute = ApiImageStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiImageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/middleware-test': typeof MiddlewareTestRoute
  '/tools-test': typeof ToolsTestRoute
  '/$provider/$feature': typeof ProviderFeatureRoute
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRouteWithChildren
  '/api/middleware-test': typeof ApiMiddlewareTestRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/tools-test': typeof ApiToolsTestRoute
  '/api/transcription': typeof ApiTranscriptionRouteWithChildren
  '/api/tts': typeof ApiTtsRouteWithChildren
  '/api/video': typeof ApiVideoRouteWithChildren
  '/$provider/': typeof ProviderIndexRoute
  '/api/image/stream': typeof ApiImageStreamRoute
  '/api/transcription/stream': typeof ApiTranscriptionStreamRoute
  '/api/tts/stream': typeof ApiTtsStreamRoute
  '/api/video/stream': typeof ApiVideoStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/middleware-test': typeof MiddlewareTestRoute
  '/tools-test': typeof ToolsTestRoute
  '/$provider/$feature': typeof ProviderFeatureRoute
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRouteWithChildren
  '/api/middleware-test': typeof ApiMiddlewareTestRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/tools-test': typeof ApiToolsTestRoute
  '/api/transcription': typeof ApiTranscriptionRouteWithChildren
  '/api/tts': typeof ApiTtsRouteWithChildren
  '/api/video': typeof ApiVideoRouteWithChildren
  '/$provider': typeof ProviderIndexRoute
  '/api/image/stream': typeof ApiImageStreamRoute
  '/api/transcription/stream': typeof ApiTranscriptionStreamRoute
  '/api/tts/stream': typeof ApiTtsStreamRoute
  '/api/video/stream': typeof ApiVideoStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/middleware-test': typeof MiddlewareTestRoute
  '/tools-test': typeof ToolsTestRoute
  '/$provider/$feature': typeof ProviderFeatureRoute
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRouteWithChildren
  '/api/middleware-test': typeof ApiMiddlewareTestRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/tools-test': typeof ApiToolsTestRoute
  '/api/transcription': typeof ApiTranscriptionRouteWithChildren
  '/api/tts': typeof ApiTtsRouteWithChildren
  '/api/video': typeof ApiVideoRouteWithChildren
  '/$provider/': typeof ProviderIndexRoute
  '/api/image/stream': typeof ApiImageStreamRoute
  '/api/transcription/stream': typeof ApiTranscriptionStreamRoute
  '/api/tts/stream': typeof ApiTtsStreamRoute
  '/api/video/stream': typeof ApiVideoStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/middleware-test'
    | '/tools-test'
    | '/$provider/$feature'
    | '/api/chat'
    | '/api/image'
    | '/api/middleware-test'
    | '/api/summarize'
    | '/api/tools-test'
    | '/api/transcription'
    | '/api/tts'
    | '/api/video'
    | '/$provider/'
    | '/api/image/stream'
    | '/api/transcription/stream'
    | '/api/tts/stream'
    | '/api/video/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/middleware-test'
    | '/tools-test'
    | '/$provider/$feature'
    | '/api/chat'
    | '/api/image'
    | '/api/middleware-test'
    | '/api/summarize'
    | '/api/tools-test'
    | '/api/transcription'
    | '/api/tts'
    | '/api/video'
    | '/$provider'
    | '/api/image/stream'
    | '/api/transcription/stream'
    | '/api/tts/stream'
    | '/api/video/stream'
  id:
    | '__root__'
    | '/'
    | '/middleware-test'
    | '/tools-test'
    | '/$provider/$feature'
    | '/api/chat'
    | '/api/image'
    | '/api/middleware-test'
    | '/api/summarize'
    | '/api/tools-test'
    | '/api/transcription'
    | '/api/tts'
    | '/api/video'
    | '/$provider/'
    | '/api/image/stream'
    | '/api/transcription/stream'
    | '/api/tts/stream'
    | '/api/video/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MiddlewareTestRoute: typeof MiddlewareTestRoute
  ToolsTestRoute: typeof ToolsTestRoute
  ProviderFeatureRoute: typeof ProviderFeatureRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiImageRoute: typeof ApiImageRouteWithChildren
  ApiMiddlewareTestRoute: typeof ApiMiddlewareTestRoute
  ApiSummarizeRoute: typeof ApiSummarizeRoute
  ApiToolsTestRoute: typeof ApiToolsTestRoute
  ApiTranscriptionRoute: typeof ApiTranscriptionRouteWithChildren
  ApiTtsRoute: typeof ApiTtsRouteWithChildren
  ApiVideoRoute: typeof ApiVideoRouteWithChildren
  ProviderIndexRoute: typeof ProviderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools-test': {
      id: '/tools-test'
      path: '/tools-test'
      fullPath: '/tools-test'
      preLoaderRoute: typeof ToolsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/middleware-test': {
      id: '/middleware-test'
      path: '/middleware-test'
      fullPath: '/middleware-test'
      preLoaderRoute: typeof MiddlewareTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$provider/': {
      id: '/$provider/'
      path: '/$provider'
      fullPath: '/$provider/'
      preLoaderRoute: typeof ProviderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video': {
      id: '/api/video'
      path: '/api/video'
      fullPath: '/api/video'
      preLoaderRoute: typeof ApiVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcription': {
      id: '/api/transcription'
      path: '/api/transcription'
      fullPath: '/api/transcription'
      preLoaderRoute: typeof ApiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools-test': {
      id: '/api/tools-test'
      path: '/api/tools-test'
      fullPath: '/api/tools-test'
      preLoaderRoute: typeof ApiToolsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summarize': {
      id: '/api/summarize'
      path: '/api/summarize'
      fullPath: '/api/summarize'
      preLoaderRoute: typeof ApiSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/middleware-test': {
      id: '/api/middleware-test'
      path: '/api/middleware-test'
      fullPath: '/api/middleware-test'
      preLoaderRoute: typeof ApiMiddlewareTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$provider/$feature': {
      id: '/$provider/$feature'
      path: '/$provider/$feature'
      fullPath: '/$provider/$feature'
      preLoaderRoute: typeof ProviderFeatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video/stream': {
      id: '/api/video/stream'
      path: '/stream'
      fullPath: '/api/video/stream'
      preLoaderRoute: typeof ApiVideoStreamRouteImport
      parentRoute: typeof ApiVideoRoute
    }
    '/api/tts/stream': {
      id: '/api/tts/stream'
      path: '/stream'
      fullPath: '/api/tts/stream'
      preLoaderRoute: typeof ApiTtsStreamRouteImport
      parentRoute: typeof ApiTtsRoute
    }
    '/api/transcription/stream': {
      id: '/api/transcription/stream'
      path: '/stream'
      fullPath: '/api/transcription/stream'
      preLoaderRoute: typeof ApiTranscriptionStreamRouteImport
      parentRoute: typeof ApiTranscriptionRoute
    }
    '/api/image/stream': {
      id: '/api/image/stream'
      path: '/stream'
      fullPath: '/api/image/stream'
      preLoaderRoute: typeof ApiImageStreamRouteImport
      parentRoute: typeof ApiImageRoute
    }
  }
}

interface ApiImageRouteChildren {
  ApiImageStreamRoute: typeof ApiImageStreamRoute
}

const ApiImageRouteChildren: ApiImageRouteChildren = {
  ApiImageStreamRoute: ApiImageStreamRoute,
}

const ApiImageRouteWithChildren = ApiImageRoute._addFileChildren(
  ApiImageRouteChildren,
)

interface ApiTranscriptionRouteChildren {
  ApiTranscriptionStreamRoute: typeof ApiTranscriptionStreamRoute
}

const ApiTranscriptionRouteChildren: ApiTranscriptionRouteChildren = {
  ApiTranscriptionStreamRoute: ApiTranscriptionStreamRoute,
}

const ApiTranscriptionRouteWithChildren =
  ApiTranscriptionRoute._addFileChildren(ApiTranscriptionRouteChildren)

interface ApiTtsRouteChildren {
  ApiTtsStreamRoute: typeof ApiTtsStreamRoute
}

const ApiTtsRouteChildren: ApiTtsRouteChildren = {
  ApiTtsStreamRoute: ApiTtsStreamRoute,
}

const ApiTtsRouteWithChildren =
  ApiTtsRoute._addFileChildren(ApiTtsRouteChildren)

interface ApiVideoRouteChildren {
  ApiVideoStreamRoute: typeof ApiVideoStreamRoute
}

const ApiVideoRouteChildren: ApiVideoRouteChildren = {
  ApiVideoStreamRoute: ApiVideoStreamRoute,
}

const ApiVideoRouteWithChildren = ApiVideoRoute._addFileChildren(
  ApiVideoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MiddlewareTestRoute: MiddlewareTestRoute,
  ToolsTestRoute: ToolsTestRoute,
  ProviderFeatureRoute: ProviderFeatureRoute,
  ApiChatRoute: ApiChatRoute,
  ApiImageRoute: ApiImageRouteWithChildren,
  ApiMiddlewareTestRoute: ApiMiddlewareTestRoute,
  ApiSummarizeRoute: ApiSummarizeRoute,
  ApiToolsTestRoute: ApiToolsTestRoute,
  ApiTranscriptionRoute: ApiTranscriptionRouteWithChildren,
  ApiTtsRoute: ApiTtsRouteWithChildren,
  ApiVideoRoute: ApiVideoRouteWithChildren,
  ProviderIndexRoute: ProviderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
