/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSettlementsRouteImport } from './routes/api/settlements'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiDisputesRouteImport } from './routes/api/disputes'
import { Route as LayoutSettlementsRouteImport } from './routes/_layout/settlements'
import { Route as LayoutOrdersRouteImport } from './routes/_layout/orders'
import { Route as LayoutDisputesRouteImport } from './routes/_layout/disputes'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettlementsRoute = ApiSettlementsRouteImport.update({
  id: '/api/settlements',
  path: '/api/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisputesRoute = ApiDisputesRouteImport.update({
  id: '/api/disputes',
  path: '/api/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettlementsRoute = LayoutSettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutOrdersRoute = LayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDisputesRoute = LayoutDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => LayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disputes': typeof LayoutDisputesRoute
  '/orders': typeof LayoutOrdersRoute
  '/settlements': typeof LayoutSettlementsRoute
  '/api/disputes': typeof ApiDisputesRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/search': typeof ApiSearchRoute
  '/api/settlements': typeof ApiSettlementsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disputes': typeof LayoutDisputesRoute
  '/orders': typeof LayoutOrdersRoute
  '/settlements': typeof LayoutSettlementsRoute
  '/api/disputes': typeof ApiDisputesRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/search': typeof ApiSearchRoute
  '/api/settlements': typeof ApiSettlementsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/disputes': typeof LayoutDisputesRoute
  '/_layout/orders': typeof LayoutOrdersRoute
  '/_layout/settlements': typeof LayoutSettlementsRoute
  '/api/disputes': typeof ApiDisputesRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/search': typeof ApiSearchRoute
  '/api/settlements': typeof ApiSettlementsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disputes'
    | '/orders'
    | '/settlements'
    | '/api/disputes'
    | '/api/orders'
    | '/api/search'
    | '/api/settlements'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disputes'
    | '/orders'
    | '/settlements'
    | '/api/disputes'
    | '/api/orders'
    | '/api/search'
    | '/api/settlements'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/disputes'
    | '/_layout/orders'
    | '/_layout/settlements'
    | '/api/disputes'
    | '/api/orders'
    | '/api/search'
    | '/api/settlements'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  ApiDisputesRoute: typeof ApiDisputesRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSettlementsRoute: typeof ApiSettlementsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settlements': {
      id: '/api/settlements'
      path: '/api/settlements'
      fullPath: '/api/settlements'
      preLoaderRoute: typeof ApiSettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/disputes': {
      id: '/api/disputes'
      path: '/api/disputes'
      fullPath: '/api/disputes'
      preLoaderRoute: typeof ApiDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settlements': {
      id: '/_layout/settlements'
      path: '/settlements'
      fullPath: '/settlements'
      preLoaderRoute: typeof LayoutSettlementsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/orders': {
      id: '/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof LayoutOrdersRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/disputes': {
      id: '/_layout/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof LayoutDisputesRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutDisputesRoute: typeof LayoutDisputesRoute
  LayoutOrdersRoute: typeof LayoutOrdersRoute
  LayoutSettlementsRoute: typeof LayoutSettlementsRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutDisputesRoute: LayoutDisputesRoute,
  LayoutOrdersRoute: LayoutOrdersRoute,
  LayoutSettlementsRoute: LayoutSettlementsRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  ApiDisputesRoute: ApiDisputesRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSettlementsRoute: ApiSettlementsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
